# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#intro"
  weight = 10

[[main]]
  name = "General Info"
  url = "#public_info"
  weight = 20

[[main]]
  name = "Patient Info"
  url = "#patient_info"
  weight = 30

[[main]]
  name = "Portal"
  url = "#online_portal"
  weight = 31

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 32 

[[main]]
  name = "Stroke Info"
  url = "#stroke_info"
  weight = 33

[[main]]
  name = "Handbook"
  url = "#caregiver_handbook"
  weight = 34

[[main]]
  name = "Image Gallery"
  url = "#gallery"
  weight = 35

[[main]]
  name = "PWA Testimonies"
  url = "#pwa_testimonies"
  weight = 36

[[main]]
  name = "Caregiver Testimonies"
  url = "#caregiver_testimonies"
  weight = 37

[[main]]
  name = "TMS Lab"
  url = "#tms"
  weight = 38

[[main]]
  name = "CSA"
  url = "#tms"
  weight = 39

# [[main]]
#   name = "Dissemination"
#   url = "#dissemination"
#   weight = 60

# [[main]]
#   name = "Contact"
#   url = "#contact"
#   weight = 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
